import Head from 'next/head';
import React, { ReactElement } from 'react';

interface Props {
  children: ReactElement;
}

const Layout = ({ children }: Props): ReactElement => {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Twitter.ico" />
      </Head>

      <main className="flex">{children}</main>
    </>
  );
};

export default Layout;
